### ISSUE TITLE
Error: spawn "C:/Program Files (x86)/MSBuild/14.0/Bin/MSBuild.exe" ENOENT

### ISSUE THREAD

**Issue by platonicvizard** [josefjura/node-msbuild#2]
Hello, I'm getting the error below. I'm not sure if it is a node version issue, can you please let me know? Thanks

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn "C:/Program Files (x86)/MSBuild/14.0/Bin/MSBuild.exe" ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "O:\\Program Files\\nodejs\\node.exe" "O:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "publish"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node publish.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at node publish.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the econet package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!  node publish.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls econet
npm ERR! There is likely additional logging output above.

------Code-------------------------------------------
var msbuild = require('node-msbuild');
var path = require('path');

// Initialize builder 
var builder = new msbuild.MsBuild({ MsBuildPath: '\"C:/Program Files (x86)/MSBuild/14.0/Bin/MSBuild.exe\"' });

// Build options 
var options = {
    Rebuild: true,
    DeployOnBuild: true,
    SolutionFile: path.join(__dirname, "server/server.sln"),
    PublishProfile: path.join(__dirname, "server/App_Data/PublishProfiles/WebDeploy.pubxml")
};

//Run builds 
builder.build(options)
    .then(function (results) {
        console.log("Called params : " + results.CmdLine);
        console.log("Result code: " + results.Code);

    });

**Comment by platonicvizard** [comment]
changing to C:/Windows/Microsoft.NET/Framework64/v4.0.30319/MSBuild.exe fixed the issue.

**Comment by jitendrasoni** [comment]
I am getting the same issue, where did you change the location?

**Comment by josefjura** [comment]
I can't test this right now, but the location is supplied by you, when creating the MsBuild object (see Readme). It doesn't check if the path is valid so you you need to make sure it's a real path to msbuild.exe.

**Comment by jitendrasoni** [comment]
Your point is valid and it makes sense, in my case actually MSBuild 15 was not installed and by default it was referring to MSBuild 12, I downloaded and installed MSBuild 15 and it worked for me.

**Comment by josefjura** [comment]
Great to hear that ;)
